frontend-watcher:
  build: .

  # DEV: Uncomment image & comment out dockerfile to skip building from scratch
  # image: lmorchard/testpilot_frontend_watcher:latest
  dockerfile: Dockerfile-frontend-build

  ports:
    - "9966:9966"
    - "35729:35729"
  volumes:
    - .:/app
  environment:
    - NODE_ENV=development
  command:
    ./bin/run-frontend-watch.sh
server:
  build: .

  # DEV: Uncomment image & comment out dockerfile to skip building from scratch
  # image: mozilla/testpilot:latest
  dockerfile: Dockerfile

  ports:
    - "8000:8000"
  # HACK: escalate to root user in dev, because we need to be able to write
  # file uploads to /app/media. Production will use Amazon S3
  user: root
  volumes:
    - .:/app
  command:
    ./bin/run-dev.sh
  environment:
    - PYTHONUNBUFFERED=1
    - PYTHONDONTWRITEBYTECODE=1
    - DATABASE_URL=${DATABASE_URL}
    - DEBUG=True
    - STATICINTEGRITY_CACHE_TTL=1
    - INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME}
    - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
    - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
    - ALLOWED_HOSTS=testpilot.dev
    - SECRET_KEY=${SECRET_KEY}
    - FXA_ACCESS_TOKEN_URL=https://oauth-stable.dev.lcip.org/v1/token
    - FXA_AUTHORIZE_URL=https://oauth-stable.dev.lcip.org/v1/authorization
    - FXA_PROFILE_URL=https://stable.dev.lcip.org/profile/v1/profile
    - FXA_CLIENT_ID=${FXA_CLIENT_ID}
    - FXA_SECRET_KEY=${FXA_SECRET_KEY}
    - DATADOG_API_KEY=${DATADOG_API_KEY}
    - DATADOG_APP_KEY=${DATADOG_APP_KEY}
    - DJANGO_LOG_LEVEL=DEBUG
    - DJANGO_LOG_FORMAT=json
