env:
  browser: true

extends:
  - eslint:recommended
  - airbnb-base

root: true

rules:
  import/newline-after-import: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off

  arrow-parens: off
  comma-dangle: [error, never]
  consistent-return: warn
  func-names: off
  global-require: warn
  indent: [error, 2, {SwitchCase: 1}]
  max-len: off
  no-console: warn
  no-extra-boolean-cast: off
  no-multi-spaces: off
  no-param-reassign: off
  no-plusplus: off
  no-return-assign: warn
  no-use-before-define: [error, nofunc]
  object-curly-spacing: off
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-rest-params: off
  prefer-template: off
  quote-props: off
  space-before-function-paren: off
